# Generated by Django 4.1 on 2022-10-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=30)),
                ('Author_Name', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('Book_Type', models.CharField(choices=[('Non-Fiction', 'Non-Fiction'), ('Edited', 'Edited'), ('Fiction', 'Fiction'), ('Reference', 'Reference')], max_length=20)),
                ('Is_Deleted', models.CharField(default='n', max_length=5)),
            ],
        ),
    ]
