# Generated by Django 4.1 on 2022-10-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_field_book_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='Book_Type',
            field=models.CharField(choices=[('Non-Fiction', 'Non-Fiction'), ('Edited', 'Edited'), ('Fiction', 'Fiction'), ('Reference', 'Reference')], default='Reference', max_length=20),
        ),
    ]
